# Generated by Django 5.2.7 on 2026-05-27 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogSimilarity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_archive_name', models.CharField(max_length=255)),
                ('source_catalog', models.CharField(max_length=512)),
                ('target_catalog', models.CharField(max_length=512)),
                ('similarity_score', models.FloatField()),
            ],
            options={
                'indexes': [models.Index(fields=['zip_archive_name', 'source_catalog'], name='readfile_ca_zip_arc_21ab15_idx')],
                'unique_together': {('zip_archive_name', 'source_catalog', 'target_catalog')},
            },
        ),
        migrations.CreateModel(
            name='PDFDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_archive_name', models.CharField(max_length=255)),
                ('relative_path', models.CharField(max_length=512)),
                ('file_name', models.CharField(max_length=255)),
                ('extracted_text', models.TextField(blank=True, null=True)),
                ('text_length', models.IntegerField(blank=True, null=True)),
                ('top_words', models.JSONField(blank=True, null=True)),
                ('wordcloud_data', models.JSONField(blank=True, null=True)),
                ('catalog_path', models.CharField(max_length=512)),
                ('catalog_name', models.CharField(max_length=255)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('quarter', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['zip_archive_name'], name='readfile_pd_zip_arc_7784d6_idx'), models.Index(fields=['catalog_path'], name='readfile_pd_catalog_8c303c_idx'), models.Index(fields=['catalog_name'], name='readfile_pd_catalog_0b71fe_idx')],
                'unique_together': {('zip_archive_name', 'relative_path')},
            },
        ),
        migrations.CreateModel(
            name='WordCluster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zip_archive_name', models.CharField(max_length=255)),
                ('catalog_path', models.CharField(max_length=512)),
                ('algorithm', models.CharField(max_length=50)),
                ('parameters', models.JSONField(default=dict)),
                ('clusters_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('zip_archive_name', 'catalog_path', 'algorithm')},
            },
        ),
    ]
